### ISSUE TITLE
ImportError: No module named ext

### ISSUE THREAD

**Issue by nthomas51** [JagandeepBrar/Plex-Assistant-Bot#1]
Hi, thanks for your work on this bot. 

I tried starting it up and got the following error

`Traceback (most recent call last):
  File "start.py", line 1, in <module>
    from backend import config, constants, logger
  File "/home/nigel/PlexAssistant/backend/config.py", line 6, in <module>
    from backend.api import telegram, sonarr, radarr, ombi
  File "/home/nigel/PlexAssistant/backend/api/telegram.py", line 1, in <module>
    from telegram.ext import Updater
ImportError: No module named ext`

I tried renaming the telegram.py file and then editing the code by just following the errors but then I got this error

`Traceback (most recent call last):
  File "start.py", line 29, in <module>
    start()
  File "start.py", line 13, in start
    config.initialize()
  File "/home/nigel/Plex-Assistant-Bot-master/backend/config.py", line 12, in initialize
    parseConfig()
  File "/home/nigel/Plex-Assistant-Bot-master/backend/config.py", line 30, in parseConfig
    parseTelegram()
  File "/home/nigel/Plex-Assistant-Bot-master/backend/config.py", line 118, in parseTelegram
    telegram.api = parser['TELEGRAM']['BOT_TOKEN']
NameError: global name 'telegram' is not defined
2019-02-07 23:22:14,453 - main.start - WARNING - Successfully closed Plex Assistant!`

Any ideas on how to fix it? I'm really excited to start using this bot!

**Comment by jagandeepbrar** [comment]
Hey there!

For the first error, it looks like you do not have the modules installed as required. Let's start by reverting back to the beginning, and start over (undo your code changes).

Once you have a fresh install, in the root directory of the project, run `pip3 install -r docs/requirements.txt`. If for whatever reason that does not work, you can manually install each module through pip using `pip3 install <module>`. These modules as of now are `python-telegram-bot`, `colored`, and `requests`. 

You can ensure these modules are installed after you are finished by typing `pip3 list`, and you should see the 3 modules in the list somewhere. 

Now for the second issue, it looks like there is an issue with your config.ini. Did you copy/move the `config.ini` in the data folder and fill in the correct data? Ensure that `config.ini` is still in the data folder. If it is there and the error still persists after fixing the modules as noted above, can you send me a screenshot of the file (blocking out any confidential information like the bot token, API tokens, etc.).

**Comment by nthomas51** [comment]
Thanks for responding so quickly. I started over with a fresh download and double checked that the 3 modules were installed. As a side note, I have python 2.7 and 3.5 installed - there's a separate service that won't work on anything newer than 2.7.

After running "python3.5 start.py" I now I get the error below:

`Traceback (most recent call last):
  File "start.py", line 1, in <module>
    from backend import config, constants, logger
  File "/home/nigel/PlexAssistant/backend/config.py", line 1, in <module>
    import configparser
  File "/usr/lib/python3.5/configparser.py", line 141, in <module>
    from collections.abc import MutableMapping
  File "/usr/lib/python3.5/collections/__init__.py", line 32, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/usr/lib/python3.5/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.`

Here's the screenshot of the .ini file.

![config](https://user-images.githubusercontent.com/16511224/52515745-9e06cc80-2bed-11e9-97c8-731165610754.png)

**Comment by jagandeepbrar** [comment]
Hmm, that's definitely strange. I have Python 3.7.2 installed on my MacOS machine (which it looks like you are running based off the font in the screenshot), but also have 3.5.2 installed on my ChromeOS laptop and it runs fine on that machine as well.

Have you tried updating the version of Python you have? Configparser has been available in Python for many iterations, including 3.5 as noted by the documentation [here](https://docs.python.org/3.5/library/configparser.html). 

It sounds like you may have a corrupted installation of Python, since I can't seem to come up with any other reason that this might be happening right now. You can try running `pip3 install configparser` to install the latest version of the module, but it should be built-in.

Just to confirm, you used `pip` for the 3.5 installation? When you have 2.x and 3.x installed, it has different versions for each.

**Comment by nthomas51** [comment]
So, I fixed it. I had to forcibly install a newer version of pip (which I'm sure is going to break something else eventually) and then install the missing 3.x modules to the 3.7 directory since using -t since pip still insisted on looking at the 2.7 paths. It's working like a charm for now. Thanks!
